### ISSUE TITLE
[Suggestion]: Allow different Layouts

### ISSUE THREAD

**Issue by maymage** [bragefuglseth/keypunch#16]
## Problem Description
I'd like to play with or exercise a new keyboard layout, but I can't 
do that with the app nor can I see the layout on the physical keyboard. 

## Proposed Solutioin
Allow using a different layout and show the desired keyboard layout, if requested, in a separate window, 
on the fly or constantly. 

## Workaround
Change the layout in Settings, open a picture of the desired layout in Loupe. 
But that's not fancy. 

- [x] This suggestion is compatible with the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig)

**Comment by bragefuglseth** [comment]
Hi, and thanks for the suggestion! While this is a cool idea, it would also add a lot of complexity to the app for something that can already be configured through the system settings, and potentially introduce confusion if people accidentially switch layouts / forget that they have done so previously.

By the way, if you press the three dots on an input method in Settings and choose "Show Keyboard Layout", you'll get an interactive preview of the layout that's way better than anything I'd ever implement for Keypunch :slightly_smiling_face: 

![Skjermbilde fra 2024-06-08 00-03-13](https://github.com/bragefuglseth/keypunch/assets/91388039/47827c38-47d8-45a9-9cdc-491adfe098a7)
