### ISSUE TITLE
[Bug]: Restart button not accessible on mobile

### ISSUE THREAD

**Issue by bragefuglseth** [bragefuglseth/keypunch#18]
> I'd also be happy to hear more about how the app works on mobile in general. I don't have a Linux phone to test it with myself currently.

One thing that might be improved, after you start typing the top bar with the settings disappears. On desktop that's not too bad because you can press ESC, but on the setup I described here there is no easy access to that key on the default phosh keyboard, you have only numbers and letters and special characters but no control keys. If you set the timer to 10 minutes you can't access the settings for 10 minutes, unless of course killing the app.

![20240608_23h40m15s_grim](https://github.com/bragefuglseth/keypunch/assets/4840355/cf62e516-2455-4ae7-bff5-b7c0c7b02c16)

_Originally posted by @heldderarbeit in https://github.com/bragefuglseth/keypunch/issues/15#issuecomment-2156197006_

**Comment by bragefuglseth** [comment]
With a pointing device, a restart button is displayed on hover. We can make the same thing happen upon a screen click on mobile.

**Comment by bragefuglseth** [comment]
@heldderarbeit, would you mind testing this locally on your device?

**Comment by heldderarbeit** [comment]
Sorry, I'm not being able to build the software on pmOS. cargo build fails at finding libadwaita-1.pc, despite /usr/lib/pkgconfig/ being in my PKG_CONFIG_PATH. And this is where my knowledge about compiling Rust on Alpine ends.

**Comment by bragefuglseth** [comment]
Have you tried to build it with Flatpak?

**Comment by heldderarbeit** [comment]
> Also @heldderarbeit install `libadwaita-dev`

As I've written in the first line of code output, it's already installed.

**Comment by ashrude** [comment]
Aight well apparently I can't read.

What I've done is installed builder on pmos through flatpak, it builds the application using flatpak and it works fine for me.

**Comment by bragefuglseth** [comment]
Great, thanks for helping out with testing!

**Comment by ashrude** [comment]
Sorry, I was talking about how it built fine. 

Pressing near the restart button does make it appear, but perhaps it would be better if tapping anywhere on the top bar would show the close/restart button. Currently you kinda have to know where to tap

**Comment by bragefuglseth** [comment]
Ah, I see what’s wrong now.

**Comment by bragefuglseth** [comment]
Try the latest commit ^

**Comment by ashrude** [comment]
It’s good, however the buttons stay there once you start typing. For consistency’s sake it might be better if it disappears again after a timeout or once you start typing.

However the chances someone is going to notice that are slim because they’ll only make the bar visible if they want to restart or close the app, and it doesn’t stop you from taking the test or anything so..

**Comment by bragefuglseth** [comment]
It should disappear when typing starts again, at least it does on desktop. Will look into it tomorrow.

**Comment by bragefuglseth** [comment]
Try now

**Comment by ashrude** [comment]
Sorry, I'll have to look at it further tomorrow. There's still something weird going on, now it's back to not activating at all on the phone.

**Comment by ashrude** [comment]
Nvm! on line 53 changing `device.timestamp() > imp.cursor_hidden_timestamp.get()` to `device.timestamp() >= imp.cursor_hidden_timestamp.get()` fixes the issue.

**Comment by bragefuglseth** [comment]
It should work now! Mind testing once more @ashrude?

**Comment by ashrude** [comment]
Works perfectly

**Comment by bragefuglseth** [comment]
Great! Thanks again for your help.
