### ISSUE TITLE
[Language Request]: Ukrainian

### ISSUE THREAD

**Issue by xalt7x** [bragefuglseth/keypunch#21]
### English Name

Ukrainian

### Native Name

Українська

### Syntax

Ukrainian is an East Slavic language. It uses a Cyrillic alphabet, almost identical to some other Slavic languages (Bulgarian, Belarusian), except that it has some extra letters (і - U+0456, ї - U+0457, є - U+0454) as well as Ukrainian apostrophe symbol (ʼ - U+02BC). Sentences and proper nouns begin with a capitalized letter. The punctuation marks used are , ; : to break up sentences, and . ! ? to end them. Punctuation marks come directly after their corresponding words, and are followed by a space before the next word. Expressions can be wrapped in typewriter quotation marks " ".

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, thanks for the request! I've made a demo implementation based on the information you've provided, and it's ready for testing. You can build the app from source by following the instructions in CONTRIBUTING.md, and select Ukranian in the Text Language dialog. Let me know if it looks good or if something should be changed.

**Comment by xalt7x** [comment]
@UrtsiSantsi 

> @xalt7x: Isn't it correct to use „ “ instead of " "? Or is it « » instead?

Thanks for asking. I believe that all of these quotation marks are valid for Ukrainian language.   
The most used are straight quotation marks ("") , as in English, and chevrons  («») .   

[Gengo style guide](https://gengo.com/uk/translators/resources/style-guide/) got it right:

> Ukrainian quotation marks are the same as the English ones, i.e. consist of opening and ending curly quotation marks (“…”).     Straight quotation marks are accepted. In documentation (help files, brochures, license agreements, EULAs) — chevrons («») must be used. English straight quotation marks (“”) should be used when translating software texts (UI options included) and texts for Web pages.   
> **_Note: It is important to remember that a full stop is to be placed outside the quotation marks and not inside as it is in English._**

I personally believe that typing application should use straight quotation marks ("") for Ukrainian.
On the picture below we can see [standard for Linux Ukrainian Unicode keyboard layout](https://r2u.org.ua/wiki/keyboard/UkrainianUnicode)

![KB_Ukrainian_Unicode](https://github.com/bragefuglseth/keypunch/assets/44649402/c29bb019-4c44-46f7-9371-9d1f3e5b0412)

I'll provide keyboard shortcuts from this layout using keys of English (US) keyboard layout that in the same place as Ukrainian characters.
- `Shift + 2` produces straight quotation marks (“”)
- `Right Alt + <` produces «  | `Right Alt + <` produces »
- `Right Alt + Shift + <` produces „  | `Right Alt + Shift + <` produces “

As you can see, straight quotation marks are the easiest to type. Hence it's the most popular symbol for quotation in Ukrainian. And that's why I believe that it should be used in Keypunch. Also, for some unknown reason I can't type «» in Firefox on Linux.

@bragefuglseth ,
Thanks for implementing this! While comparing it with English, I don't see anything particularly unusual.
The only thing that remains mysterious to me is the meaning of the special code for Ukrainian language:
```
Language::Ukranian => simple_generic(&language.to_string(), " "),
...
Language::Ukranian => advanced_generic(&language.to_string(), " ", GENERIC_PUNCTUATION)
```

**Comment by bragefuglseth** [comment]
> The only thing that remains mysterious to me is the meaning of the special code for Ukrainian language

Nothing to worry about! It's just the code syntax being a little confusing. The `|` before each language is actually an `OR` operator, so the function call after `Language::Ukranian` is used if the language is Ukranian OR any of the preceding ones. Ukranian just happens to be last alphabetically.

**Comment by bragefuglseth** [comment]
Thanks for the help with getting Ukranian into Keypunch!
