### ISSUE TITLE
[Suggestion]: Treat French special characters like Monkeytype does

### ISSUE THREAD

**Issue by idoric** [bragefuglseth/keypunch#22]
### Context
The most common French keyboard layout (AZERTY) doesn't allow to type certain French characters. The French rely heavily on the autocorrection systems of word processors to compensate for this lack (for example "oe" is automatically replaced by "œ"). But we don't always write in a word processor, and some French people use keyboard layouts better designed for French (in particular Bépo and Ergo-L).
And these users want to practice typing these characters, and get the right reflexes (for example in good French typography the exclamation point is preceded by a narrow no-break space U+202F). To satisfy everyone, Monkeytype offers a solution that is not very clean but sufficient in practice, and which has the advantage of being easily implementable.

### Monkeytype's solution
In the texts to be typed in French there are no special characters (for example the word "cœur" is written "coeur", as a child would write), and then certain characters typed by users are automatically replaced:

- œ is replaced by oe
- æ is replaced by ae
- … (one character) is replaced by ... (three characters)
- NNBSP (U+202F) and NBSP (U+00A0) are replaced by SPACE (U+0020)
- ’ is replaced by '
- ‑  (non-breaking hyphen), – (En Dash) and — (Em Dash) are replaced by - (Hyphen-Minus)
- (and probably others)

**Comment by bragefuglseth** [comment]
Hi, and thanks for the suggestion! This makes sense to me, but there are multiple things to take into consideration if we're going to do it:

- The replacements don't make sense in all languages. For instance, the Nordic keyboard layout has the letter Æ as a proper key, and replacing it with "ae" would look alien to Norwegians and Danes. So we'd have to special case both the replacement and input logic for when French is chosen as the text language.
- Special casing adds code complexity, especially for the input machinery.

I think we can come to a solution, but it needs some thinking through first.

**Comment by idoric** [comment]
That would be really great!

**Comment by idoric** [comment]
Here are the ones I thought about:

Œ - OE
Æ - AE
… - ...
’⁽¹⁾ - '
There are no strict rules regarding the use of the non-breaking hyphen, so I would think that the easiest way to satisfy everyone would be for the hyphen (- U+002D) and the non-breaking hyphen (‑ U+2011) to both be an alias of the other.

⁽¹⁾ In France it is called the typographic apostrophe (apostrophe typographique)
