### ISSUE TITLE
[Language Request]: Hungarian

### ISSUE THREAD

**Issue by danieluhrinyi** [bragefuglseth/keypunch#27]
### English Name

Hungarian

### Native Name

Magyar

### Orthography

**Alphabet:** Hungarian is written with the Hungarian alphabet, an extended version of the Latin alphabet. Its letters usually indicate sounds, except when morphemes are to be marked (see below). The extensions include consonants written with digraphs or a trigraph and vowel letters marked with diacritics. Long consonants are marked by a double letter (e.g. l > ll and sz > ssz) while long vowels get an acute accent (e.g. o > ó) or their umlaut is replaced with a double acute accent (ö, ü > ő, ű). Only the first letter of digraphs and of the trigraph dzs is written in upper case when capitalizing in normal text, but all letters are capitalized in acronyms and all-uppercase inscriptions.

**Word breaks:** Compound words are typically spelt as one word (without spaces) and phrases are normally spelt as more than one word (with one or more spaces), but this is not always the case. Hyphenated spelling is considered an alternative to writing as one word and is used, e.g., if a compound contains a proper name.

**Punctiation:** Very similar to that of English.

_Source and more details: [Hungarian orthography (Wikipedia)](https://en.wikipedia.org/wiki/Hungarian_orthography)_

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by danieluhrinyi** [comment]
Hey Brage,

I have just given it a quick run in all available modes (simple, advanced and custom) and they work as expected. It looks like an error-free and excellent addition to the app.

Thanks and best,
Daniel

**Comment by bragefuglseth** [comment]
Great, thanks a lot for the help!
