### ISSUE TITLE
[Language Request]: Brazilian Portuguese

### ISSUE THREAD

**Issue by ThiagoReisFreitas** [bragefuglseth/keypunch#29]
### English Name

Brazilian Portuguese

### Native Name

Português do Brasil

### Orthography

Claro! Aqui está um exemplo de texto que você pode usar para enviar uma solicitação (issue) no GitHub:

Título da Issue: Bug: Erro ao carregar a página inicial após login

Descrição:

Olá equipe de desenvolvimento,

Gostaria de relatar um bug que estou enfrentando ao tentar acessar a página inicial após realizar o login. Seguem os detalhes:

Passos para Reproduzir:

Acesse a página de login (/login).
Insira suas credenciais e clique em "Entrar".
Após o login, a página redireciona para a página inicial (/home).
A página inicial não carrega corretamente e exibe um erro.
Comportamento Esperado:
Após o login, a página inicial deveria carregar e exibir o conteúdo sem erros.

Comportamento Atual:
Ao ser redirecionado para a página inicial, a mesma exibe o seguinte erro: "Erro 500 - Internal Server Error".

Ambiente:

Sistema Operacional: Windows 10
Navegador: Google Chrome versão 91.0.4472.124
Versão do Sistema: 1.0.0
Informações Adicionais:

Anexei uma captura de tela do erro que está sendo exibido.
Testei em outros navegadores (Firefox e Edge) e o problema persiste.
Limpei o cache do navegador e reiniciei o sistema, mas o erro continua.
Anexos:

captura-de-tela-erro.png
Agradeço desde já pela atenção e fico à disposição para fornecer mais informações se necessário.

At

### Implementation Assistance

- [ ] I am proficient enough in this language to spot mistakes and unnatural words
- [ ] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, thanks for the request. The orthography section contains AI generated text that doesn't have anything to do with this at all. I'd appreciate if it was changed to contain the information needed to set up decent text generation instead.

**Comment by bragefuglseth** [comment]
Closing because of lack of information.
