### ISSUE TITLE
[Language Request]: Russian

### ISSUE THREAD

**Issue by NeMo-lox** [bragefuglseth/keypunch#30]
### English Name

Misha

### Native Name

NeMo

### Orthography

Russia language

### Implementation Assistance

- [ ] I am proficient enough in this language to spot mistakes and unnatural words
- [ ] I can assist with testing and reviewing the language implementation

### Additional Information

Russia

**Comment by bragefuglseth** [comment]
Hi, thanks for opening this. To add Russian as a text language to Keypunch, I'll need the request to be more elaborate. The "name" fields should contain the name of the language, and the "Orthography" section should contain information on how the language is typed (what kind of letters there are, what kind of punctuation there is, etc.

If you're able to provide this information, just edit the request directly and notify me afterwards :slightly_smiling_face:

**Comment by bragefuglseth** [comment]
Thanks for the help, @UrtsiSantsi! Implemented in #40

**Comment by darkblaze69** [comment]
As a native Russian speaking, I think I haven't seen anybody using `« »` while typing especially fast typing. It's just the work for fancy editors to prettify these things. On the keyboards it's just not available for fast typing.

**Comment by bragefuglseth** [comment]
AFAIK there are no languages where using typewriter quotation marks (") is typographically correct, it would at least be ” and “ instead. However, I’ve found that the typographical traditions of a language often don’t align with how people casually type it out, similar to how spoken and formal written language are different in their own ways. That’s at least how it seems to be here in Norway, where « and » are used in professional typigraphy, but people use the " key in practice. Most word processors and such can transparently change typewriter quotation marks to the typographically correct ones based on the language used, so generally I’d like Keypunch to reflect which keys people actually *use* when living their lives, chatting with friends, working on assignments, etc.
