### ISSUE TITLE
[Suggestion]: Allow Ctrl+backspace to delete entire words

### ISSUE THREAD

**Issue by eldelacajita** [bragefuglseth/keypunch#32]
**Is your suggestion related to a problem? Please describe.**

It's common practice, when learning touch typing, to go back and rewrite entire words when you make a mistake. This way, you practice words as sequences instead of just separated letters.
You usually use Ctrl+backspace for this, but in Keypunch that's not working. Just the last letter gets deleted.

**Describe the solution you'd like**

Ctrl+backspace should delete entire words.

- [x] This suggestion is compatible with the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig)

Loving the app, BTW!

**Comment by bragefuglseth** [comment]
Thanks for the suggestion! This is a duplicate of #7.

**Comment by eldelacajita** [comment]
Oh, sorry I missed that one! It didn't occur to me to check the closed issues 😅
