### ISSUE TITLE
Esc doesn't work if focus is in the language search entry

### ISSUE THREAD

**Issue by UrtsiSantsi** [bragefuglseth/keypunch#35]
Esc doesn't work if focus is in the language search entry in the text language dialog.

1. Press Ctrl+,
2. The "Text language" dialog is opened and the focus is in the search entry
3. Press Esc

**Expected behavior**
The dialog should close, but it stays open.
Can also be reproduced if the dialog is opened from the menu and the search entry selected.

- [ x] I confirm that I can reproduce the bug in the Flathub version of the app.

**Comment by bragefuglseth** [comment]
Good catch! Apparently GtkSearchEntry overrides the escape key and emits its own `stop-search` signal when it's clicked. Keypunch will have to connect to that and close the dialog manually when that happens.
