### ISSUE TITLE
Multiple "Text language" dialog can be opened at the same time

### ISSUE THREAD

**Issue by UrtsiSantsi** [bragefuglseth/keypunch#36]
Multiple "Text language" dialog can be opened at the same time using the shortcut.

1. Press Ctrl+, multiple times
2. Multiple copies of the dialog are opened

**Expected behavior**
If the dialog is opened nothing should happen

- [ x] I confirm that I can reproduce the bug in the Flathub version of the app.

**Comment by bragefuglseth** [comment]
Thanks for catching that! This is fortunately an easy fix.
