### ISSUE TITLE
[Language Request]: Bulgarian

### ISSUE THREAD

**Issue by UrtsiSantsi** [bragefuglseth/keypunch#37]
### English Name

Bulgarian

### Native Name

Български

### Orthography

Bulgarian is a Slavic language. It uses a Cyrillic alphabet. Sentences and proper nouns begin with a capitalized letter. The punctuation marks used are , ; : to break up sentences, and . ! ? to end them. Punctuation marks come directly after their corresponding words, and are followed by a space before the next word. Expressions can be wrapped in typewriter quotation marks " ".

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

See [MR # 34](https://github.com/bragefuglseth/keypunch/pull/34)

**Comment by bragefuglseth** [comment]
Thanks for the contribution! If you'd like to, you can provide a name (and optionally a website) to be credited in the Orthography section of the about dialog.
