### ISSUE TITLE
[Language Request]: Portugese

### ISSUE THREAD

**Issue by coldrenatinho** [bragefuglseth/keypunch#46]
### English Name

Portuguese

### Native Name

Português

### Orthography

The Portuguese alphabet consists of 26 letters, just like the English alphabet.
However, there are a few additional letters specific to Portuguese:
Ç (cedilha): This letter represents the “soft c” sound, similar to the English “s.” It appears only before the vowels “a,” “o,” and “u.” For example, “maçã” (apple).
Â, Ê, Ô: These are circumflex-accented vowels, which indicate a different pronunciation. For instance, “pôr” (to put).
Á, É, Í, Ó, Ú: These are acute-accented vowels, emphasizing the stressed syllable. For example, “público” (public).
Ã, Õ: These are tilde-accented vowels, representing nasal sounds. For instance, “pão” (bread).
The order of the alphabet is the same as in English.
Word Separation:
In Portuguese, words are separated by spaces, just like in English.
Hyphenation is also common, especially in compound words or when joining prefixes or suffixes to a base word. For example, “guarda-chuva” (umbrella).
Punctuation:
Period (.): Used to end sentences, just like in English.
Comma (,): Used for separating items in a list or clauses within a sentence.
Question Mark (?): Indicates a question.
Exclamation Mark (!): Expresses strong emotion or emphasis.
Colon (:): Introduces a list, explanation, or quotation.
Semicolon (;): Connects related independent clauses.
Quotation Marks (" "): Used for direct speech or to enclose titles.
Parentheses ( ): Provide additional information or clarification.
Dash (—): Used for emphasis or to set off a phrase.
Ellipsis (…): Indicates omission or trailing off.
Apostrophe ('): Used for contractions and possessives (e.g., “d’água” for “of water”).

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, thanks a lot for the language request! I'll go ahead and spin up an initial implementation. You can follow the steps in CONTRIBUTING.md to build the development version the app, and choose Portugese from the language switcher to test it. Let me know if anything should be changed!

**Comment by bragefuglseth** [comment]
Portugese text generation unfortunately won't ship in Keypunch 3.0 because it hasn't been tested properly yet.

**Comment by viniciagoes** [comment]
I'm happy to assist in any way i can with Portuguese, specially Brazilian Portuguese.

**Comment by bragefuglseth** [comment]
Great! I'll go ahead and re-enable Portuguese on the main branch. You can run the project from source using the instructions in CONTRIBUTING.md, and switch to Portuguese in the Text Language dialog. I think the word list used should apply to both Brazilian Portuguese and Portuguese Portuguese.

**Comment by viniciagoes** [comment]
Sorry for the delay, I'll give it some attention from now on! Thank you for the support!

**Comment by bragefuglseth** [comment]
Does the current state of the Portugese implementation look good to you?

**Comment by bragefuglseth** [comment]
I'm doing a release, and will temporarily remove the Portuguese text generation, since I can't be sure if it's error free and high quality at the moment. Give me a heads-up here when you're able to test it, and I'll re-add it.

**Comment by bragefuglseth** [comment]
Hi, thanks a lot for volunteering! I'll re-enable Portuguese so you can test it.

> Portuguese has two "variations": Portuguese and Brazilian Portuguese
> The original Portuguese is spoken mainly in Portugal. But Portuguese in Brazil is a little different, the pronunciation is different and there are some different words and rules.

Since Keypunch only uses a word list of ~200 words, I'm not sure if there would actually be any meaningful difference between the word lists of the "original" and the Brazillian variants of Portuguese. Monkeytype's language directory, which is where Keypunch gets most of its word lists from, does not have separate lists for the two. Because of this, I'm inclined to keep the general "Portuguese" labelling. I assume that the absence of a specific Brazillian version is enough for people to know what to choose. Let me know if I'm wrong, though.

**Comment by TarsiSurdi** [comment]
Tested this out just now building the app from source and the support for Brazilian Portuguese is really good! Thank you for taking the time to implement it's text generation.

**Comment by maopequena** [comment]
Just a correction here:

> And I didn't see any "hà", it is something that is used VERY rarely, so I don't know if it needs to be added.

The word "hà" - with this specific accentuation - doesn't exist in any variant of the Portuguese language; we do have:
- "a": article, akin to "the" for female nouns;
- "à": with "crase" - which is the union of a preposition "a" and an article "a", means "for the" for female nouns, akin to "ao", used for male nouns;
- "há": from the verb "haver", means "to be";
- "hã": to express doubt/surprise, similar to "umm"/"hmm";
- "as": plural form of the article "a";
- "às": plural form of the crase "à";
- "ás": the name of the card "ace";
- "hás" and "hão": forms of the verb "haver" in the tense "presente do indicativo".

And, apart from the last two, they're all used ALL THE TIME.

I've always wondered where that "hà" came from while using the app... now I know!

**Comment by Seikm** [comment]
@maopequena 
> The word "hà" - with this specific accentuation - doesn't exist in any variant of the Portuguese language; we do have:

Well that was a really silly mistake on my part, I think I got confused back then when I was thinking about "à" lol. Really sorry about that.

> And, apart from the last two, they're all used ALL THE TIME.

I don't think I completely agree with that. "à", "há" and "ás" are rarely used outside of more formal settings, and "hã" is usually only used verbally. But that's just my experience.

That being said, if you don't want to do that, I can create a PR fixing my dumb error and adding/removing things as you wish, please let me know.

**Comment by maopequena** [comment]
> Well that was a really silly mistake on my part, I think I got confused back then when I was thinking about "à" lol. Really sorry about that.

I imagined this was a mistake, but I didn't even THINK about reporting it until today... 

> That being said, if you don't want to do that, I can create a PR fixing my dumb error and adding/removing things as you wish, please let me know.

Apart from changing "hà" to "à", I don't see the need to change any more words on the app, I think it's quite comprehensive just the way it is. 

Thank you for your quick response, @Seikm !

**Comment by Seikm** [comment]
> Apart from changing "hà" to "à", I don't see the need to change any more words on the app, I think it's quite comprehensive just the way it is.

I think it would be better to replace "hà" with "há" (I believe it's used more often than "à"), but if you want I can include both "há" and "à".

**Comment by maopequena** [comment]
> I think it would be better to replace "hà" with "há" (I believe it's used more often than "à"), but if you want I can include both "há" and "à".

Yes, please! :)
And thank you!
