### ISSUE TITLE
[Language Request]: Nepali

### ISSUE THREAD

**Issue by pakosaan** [bragefuglseth/keypunch#5]
### English Name

Nepali

### Native Name

नेपाली

### Syntax

Typing in Nepali on a keyboard involves several specific conventions related to letter usage, word splitting, and punctuation. Here's a brief overview:

### Letter Usage
1. **Devanagari Script**: Nepali is written in the Devanagari script. Each key on a Nepali keyboard corresponds to a Devanagari character rather than a Latin alphabet letter.
2. **Consonants and Vowels**: The keyboard layout includes consonants (व्यंजन) and vowels (स्वर). Vowels can appear as independent letters or as diacritic marks attached to consonants.
3. **Conjunct Consonants**: Nepali has many conjunct consonants (ligatures) which combine multiple consonants into a single character. Special keystrokes or combinations are used to type these ligatures.

### Word Splitting
1. **No Spaces within Words**: Unlike English, where spaces are used to separate all words, in Nepali, words, especially those with affixes or compound words, are written without spaces in between.
2. **Spaces between Words**: Spaces are used to separate individual words or phrases. Proper noun compounds and certain grammatical structures might appear without spaces but are considered single words.

### Punctuation Conventions
1. **Traditional Punctuation**: Nepali uses traditional punctuation marks similar to those in English, such as periods (।), commas (,), question marks (?), and exclamation marks (!).
2. **Devanagari-specific Marks**: The danda (।) is used as a full stop (equivalent to a period in English) to denote the end of a sentence.
3. **Quotation Marks**: Both Western-style (“ ”) and traditional (अनुप्रासः) quotation marks might be used.

### Keyboard Layout
1. **InScript Layout**: The most common keyboard layout for typing in Nepali is the InScript layout, which maps Devanagari characters to keys in a way that makes typing efficient.
2. **Phonetic Layouts**: Some people use phonetic keyboards where the Nepali letters are mapped to keys based on their phonetic similarity to English letters.

Understanding these conventions can help with efficient and accurate typing in Nepali, ensuring that the text adheres to proper linguistic and grammatical norms.

### Implementation Assistance

- [ ] I am proficient enough in this language to spot mistakes and unnatural words
- [ ] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Thanks for reaching out! I think I'll be able to spin up Nepali text generation with the information you provided.

Just to make sure, can you assist with testing the implementation before it's released as part of an update? If yes, check the box in the "Implementation Assistance" section :) It just involves downloading a development flatpak and running it to see if the generated text looks ok.

**Comment by bragefuglseth** [comment]
Hi, the Nepali implementation is ready for testing! To check it out, download the [latest development build](https://nightly.link/bragefuglseth/keypunch/workflows/ci/main/keypunch-x86_64.zip) and choose "नेपाली" in the language dialog. You should check if the words used are OK, and if the advanced text generation looks correct. There won't be any meaningful sentences since all the words are selected at random, but the punctuation should be on point.

**Comment by bragefuglseth** [comment]
Since the Hindi implementation is up and running successfully, I'll just close this now. The Nepali word list used is fetched from Monkeytype's repository, so it should be good enough.
