### ISSUE TITLE
[Suggestion]: Option to use monospaced font

### ISSUE THREAD

**Issue by ulysg** [bragefuglseth/keypunch#51]
**Is your suggestion related to a problem? Please describe.**
I really like using a monospaced font for typing test, like in monkeytype.com. I find it easier on the eyes.

**Describe the solution you'd like**
I've read the contributing guidelines and I saw the part about preferences. So maybe the app could have a simple toggle between proportional and monospaced font, using the default GNOME fonts, rather than a font picker.

**Describe alternatives you've considered**
The app could directly use the default monospaced font, so no preferences would be needed, but I'm not the one to choose.

**Additional context**
I don't see mention of monospaced font in the GNOME HIG, so I'm not sure about that. But Apostrophe uses it as default, and it's in the Gnome Circle.

- [ ] This suggestion is compatible with the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig)

**Comment by bragefuglseth** [comment]
Hi, and thanks for your suggestion! I've considered this myself before; the readability argument is probably why most other typing websites are using monospace. With that in mind, I think we can try switching to monospace by default before considering a preference. Let's do it for the next release and see if there are any complaints.

**Comment by bragefuglseth** [comment]
Done in https://github.com/bragefuglseth/keypunch/commit/872d5942a618c42b3fa48fb50f3de896bd6d225f for future reference

**Comment by ulysg** [comment]
It looks really good like that! Thanks a lot for your work, I'm really loving this app.

**Comment by schuelermine** [comment]
Would it be possible to add an option to switch back to a proportional font? I don’t like the monospace font.

**Comment by bragefuglseth** [comment]
Thanks for the feedback! I'll consider it. Admittedly, though, I think it's just a matter of getting used to either of them.

The app currently uses the system monospace font; we might switch to shipping a high-quality monospace font built into the app in the future. Some monspaced fonts are better suited for terminal usage than typing practice.

**Comment by bragefuglseth** [comment]
Closing this for now; future issues on the same topic will be marked as duplicates. I understand the desire for an in-app font preference, but I strongly believe we should try sticking with a font provided by the system configuration. While I'm not going to shut the door completely, it's going to take some really good arguments for this to be reconsidered.
