### ISSUE TITLE
[Language Request]: Brazilian Portuguese

### ISSUE THREAD

**Issue by viniciagoes** [bragefuglseth/keypunch#53]
### English Name

Brazilian Portuguese

### Native Name

Português Brasileiro

### Orthography

Same alphabet as English with the addition of some other characters (words with these symbols would be nice), similar to Spanish but the symbols we have are only for vowels, it depends on the keyboard layout but it's really common in the language, the symbols are ^, ~, ´, `, some of them do not appear in other vowels: the list of symbols are:
á, à, ã, â
é, ê
í
ó, õ, ô,
ú

I think i covered it all, but i'm happy to help in any way.

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

In Portuguese, all that's written nowadays is written in the same way for all the countries. Old texts may contain different spelling in a lot of words and internet texts also should be different from the pattern. Happy to help.

**Comment by bragefuglseth** [comment]
Closing in favor of #46
