### ISSUE TITLE
[Language Request]: Italiano

### ISSUE THREAD

**Issue by loviuz** [bragefuglseth/keypunch#54]
### English Name

Italian

### Native Name

Italiano

### Orthography

Similar to most used western languages.

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, and thanks for the request! I'll spin up italian text generation on the main branch. Afterwards, you can run the app from source using the instructions provided in CONTRIBUTING.md, switch to Italian in the Text Language dialog, and check if everything looks ok.

**Comment by loviuz** [comment]
A friend had already translated. I have tried to launch the application and I see text generation: everything translated in italian. The GUI is not translated, it still remains in english and I cannot find a setting to change the GUI language. Am I missing something? I have checked data/it.po and it seems fine.

**Comment by bragefuglseth** [comment]
Thanks a lot for helping out!
