### ISSUE TITLE
[Language Request]: Polish

### ISSUE THREAD

**Issue by Nesboo** [bragefuglseth/keypunch#55]
### English Name

Polish

### Native Name

Polski

### Orthography

Sure, here's a brief explanation of the Polish alphabet, word separation, and punctuation conventions in the context of typing on a keyboard:

### Polish Alphabet
The Polish alphabet consists of 32 letters, derived from the Latin alphabet with the addition of several diacritical marks:
- Standard Latin letters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, R, S, T, U, W, Y, Z
- Additional letters with diacritics: Ą, Ć, Ę, Ł, Ń, Ó, Ś, Ź, Ż

Diacritics are important as they change the pronunciation and meaning of words. For example, "a" and "ą" are different letters with distinct sounds and uses.

### Word Separation
In Polish, words are typically separated by spaces, similar to English. Compound words can be written as a single word (e.g., "samochód" for "car") or with a hyphen (e.g., "czołg-samochód" for "tank-car").

### Punctuation Conventions
Polish punctuation is similar to English with a few distinctions:
- **Periods (.)**: Used to end sentences.
- **Commas (,)**: Used extensively to separate clauses, lists, and to provide clarity.
- **Exclamation Marks (!)**: Indicate strong feelings or commands.
- **Question Marks (?)**: Used at the end of questions.
- **Quotation Marks**: Typically „this style” is used for quotes within text, while «this style» can also be used.
- **Colons (:) and Semicolons (;)**: Used similarly to English for lists and to connect related clauses.
- **Hyphens (-) and Dashes (–)**: Hyphens are used for compound words, while dashes can indicate a break in thought.

### Typing on a Keyboard
Polish keyboards have dedicated keys for the special characters with diacritics. When using a standard QWERTY keyboard:
- Letters with diacritics can often be typed using combinations of the right Alt key (AltGr) with the corresponding letter, e.g., AltGr + A = ą.
- On mobile devices, holding down the base letter will usually bring up a menu of diacritical variants.

Understanding these conventions is essential for typing correctly in Polish, ensuring proper communication and comprehension.

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, and thanks for the request! I'll spin up Polish text generation on the main branch. Afterwards, you can run the app from source using the instructions provided in CONTRIBUTING.md, switch to Polish in the Text Language dialog, and check if everything looks ok.

**Comment by bragefuglseth** [comment]
@drpetrikov has been kind enough to test the Polish text generation, and it reportedly works at it should!
