### ISSUE TITLE
[Language Request]: czech

### ISSUE THREAD

**Issue by Grejdy** [bragefuglseth/keypunch#58]
### English Name

czech

### Native Name

Čeština

### Orthography

Czech uses the classical Latin alphabet augmented with long vowels (á, é, í, ý, ó, ů, ú - the last one only at the beginning of words and in cases like "trojúhelník"=tri-angle) and letters (mostly consonants) with a hook, which replace most of the conjunctions. Specifically, these letters are š, č, ř (this makes Czech practically unique), ž, ě, ť, ď, ň... I hope I haven't forgotten any of them:-) (on the Czech keyboard these letters take up practically the whole upper number block and not all of them are there yet - the least used ones are typed by combining the keys for ˇ/' and the corresponding letter). Unlike English, czech is a synthetic language, so it embeds a lot of information in the shape of the word instead of in the structure of the sentence, which makes it possible to omit certain clause members if they are implied by the shape of other words in the sentence. Sentences in a clause are separated by "," in Czech unless they are two coordinate clauses in a conjunctive relationship and are also separated by a conjunction (usually "a"=and). Czech uses different characters for the leading („) and trailing (”) quotation marks, but these two characters are not part of the basic Czech keyboard, so many programs automatically use them to replace the English quotation marks (") that are already on the Czech keyboard, and the average Czech simply uses English quotation marks when typing. Usually a space is used before and after the hyphen (an exception is the atypical, but used, conjunction -li... e.g. "Zemřel-li, je mrtvý."). For numbers, thousands are separated by a space and tithes by a comma (so the English 1,234.567 is written as 1 234,567 in Czech).

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, and thanks for the request! I'll spin up Czech text generation on the main branch. Afterwards, you can run the app from source using the instructions provided in CONTRIBUTING.md, switch to Czech in the Text Language dialog, and check if everything looks ok.

**Comment by Grejdy** [comment]
Yes, that looks good. Maybe I'd add some more words containing o, t and n. I can think of úl, účel, ústrk, baňka, kůň, déšť, ať or šťáva (there probably doesn't need to be that many, maybe just one of each, but let's make sure you have a chance to come across them too).
And it would be wonderful if English quotation marks („”) were displayed in the text, but English quotation marks ("") would also be taken as the "correct answer" to match the behavior of word processors, but that's basically an irrelevant detail.

**Comment by bragefuglseth** [comment]
> Yes, that looks good. Maybe I'd add some more words containing ú, ť and ň. I can think of úl, účel, ústrk, baňka, kůň, déšť, ať or šťáva (there probably doesn't need to be that many, maybe just one of each, but let's make sure you have a chance to come across them too).

I've just gone ahead and appended all those to the Czech word list.

> And it would be wonderful if English quotation marks („”) were displayed in the text, but English quotation marks ("") would also be taken as the "correct answer" to match the behavior of word processors, but that's basically an irrelevant detail.

That's fully possible, and I can do it if it makes sense for Czech specifically. It's not what Keypunch does for most languages, though.

**Comment by bragefuglseth** [comment]
Thanks for the help! If you'd like to, you can provide a name (and optionally a website), and I'll credit you in the Orthography section in the about window of the app.

**Comment by Grejdy** [comment]
> That's fully possible, and I can do it if it makes sense for Czech specifically. It's not what Keypunch does for most languages, though.

Yes, it would make sense for Czech

**Comment by Grejdy** [comment]
> Thanks for the help! If you'd like to, you can provide a name (and optionally a website), and I'll credit you in the Orthography section in the about window of the app.

Thank you, but I guess I have no desire to be mentioned in Orthography.
