### ISSUE TITLE
[Bug]: Text view doesn't follow system monospace font setting

### ISSUE THREAD

**Issue by adityainduraj** [bragefuglseth/keypunch#59]
**Is your suggestion related to a problem? Please describe.**
I have set Geist Mono as the font of choice for my entire system. Keypunch is so far the only app with no option to set it as the font and doesn't set it defaultly either. 

**Describe the solution you'd like**
Either follow System Monospace font settings or give the user an option to set a font of their choosing. 

- [x] This suggestion is compatible with the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig)

**Comment by bragefuglseth** [comment]
Hi! I thought it did this. Will look into fixing the issue.

**Comment by bragefuglseth** [comment]
I've investigated the problem, and found what I think is the cause. GTK uses [fontconfig](https://www.freedesktop.org/wiki/Software/fontconfig/) to get the system monospace font. I assume that you've changed your system monospace font with GNOME Tweaks, which does, confusingly enough, [not touch fontconfig at all.](https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/306). The setting GNOME Tweaks changes, appears to be manually read by apps like Terminal, Console and Text Editor, and Keypunch would have to poke a hole in the sandbox to do the same as of now.

Making it easy to properly change the system monospace font requires changes further up in the font config stack, and is not something I think Keypunch should attempt to handle on its own. Feel free to venture up in the system and attempt to initiate improvements there, though.

For now, the [fontconfig user documentation](https://fontconfig.pages.freedesktop.org/fontconfig/fontconfig-user.html) might be of interest to you if you'd like to change the monospace font with fontconfig.

See [this issue in Fractal's tracker](https://gitlab.gnome.org/World/fractal/-/issues/1451), which is about the exact same thing.

**Comment by adityainduraj** [comment]
Thanks for the clarification. I got it working as desired, just dropping what I did here, in case someone is facing the same issue as me. I'm using the Flatpak version of Keypunch. 

1. Go to `~/.var/app/(the keypunch folder)/config` and create a folder `fontconfig`.
2. Create a file fonts.conf using `sudo nvim fonts.conf`.
3. Enter the following into it (replace font name with your desired font name).

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <!-- Set Geist as the default sans-serif font -->
  <match target="pattern">
    <test name="family" qual="any">
      <string>sans-serif</string>
    </test>
    <edit name="family" mode="assign" binding="strong">
      <string>Geist</string>
    </edit>
  </match>

  <!-- Set Geist Mono as the monospace font -->
  <match target="pattern">
    <test name="family" qual="any">
      <string>monospace</string>
    </test>
    <edit name="family" mode="assign" binding="strong">
      <string>Geist Mono</string>
    </edit>
  </match>
</fontconfig>
```

4. Restart the app.
