### ISSUE TITLE
[Language Request]: pls add turkish

### ISSUE THREAD

**Issue by rar12455** [bragefuglseth/keypunch#66]
### English Name

turkish

### Native Name

türkçe

### Orthography

Turkish is a language called "türkçe" in natively as well as, Turkish has such own family. Turkish language family is huge,
![258c609821fa689e0ca2b13d481bd16b](https://github.com/user-attachments/assets/5305b75a-3f3d-42d6-b1d6-fecfa73ce032)
I posted a PNG to make practical.
So Turkish has so much types and most used are called "Türkiye türkçesi" which was means the flavor of Turkish mostly used on turkey (Türkiye)  

Turkish is spoken mostly on 10 countries, which were :  turkey, Azerbaijan, Iran, Russia, china, Turkmenistan, Kazakhstan, Uzbekistan, Kyrgyzstan and unlikely the northern Cyprus (NCTR : NORTHERN CYPRUS TURKISH REPUBLIC*) *unofficial.

Turkish alphabet has no official directive but mostly spoken accent ("türkiye türkçesi") it uses Latin modified Latin alphabet
which modifications are : extra letter "i","ğ","ü","ş","ö"
which were like English 
but tbh the Turkish grammar is complex. (ı can help)

example : 

-- keypunch uygulamasını seviyorum. 
(ı love the keypunch app)
- **the sentence starts with predicate**

- the (ı) word on there formed "sını"

- and _**added possessive suffix**_

_**the is formed nothing because there is no adverb in turkish.**_

ı think this Orthography is enough
love from Turkey <3

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

I am master in 2 Turkish accents which were : 

Turkish (C2)
Turkmen (Native language)

for support, you can contact me  via email : rarSS@proton.me

**love from turkey <3**

**Comment by bragefuglseth** [comment]
Hi, and thanks for the language request! I’m happy to report that Turkish text generation was added in #61 a few days ago, and will arrive in the next release of Keypunch :)

**Comment by rar12455** [comment]
thanks for the relply : )

21 Ağu 2024 Çar 08:12 tarihinde Brage Fuglseth ***@***.***>
şunu yazdı:
