### ISSUE TITLE
[Bug]: Ctrl+Backspace does not work

### ISSUE THREAD

**Issue by jay-tau** [bragefuglseth/keypunch#7]
**Describe the bug**

Control+Backspace does not erase the entire word

**To Reproduce**
1. Partially type a word
2. Press control+backspace

**Expected behavior**
The entire word is deleted

**Screenshots**
N/A

**Additional context**
N/A

- [x] I confirm that I can reproduce the bug in the Flathub version of the app.

**Comment by bragefuglseth** [comment]
Thanks for reporting! The app uses its own custom input machinery
