### ISSUE TITLE
[Suggestion]: wait for correct input

### ISSUE THREAD

**Issue by dhuschde** [bragefuglseth/keypunch#70]
Add an option to wait for the user to type the correct letter before moving on to the next one, similar to how https://www.keybr.com/ does it. 
I believe this will help users learn to locate the correct keys more effectively.

**Comment by bragefuglseth** [comment]
Hi, and thanks for the suggestion! :slightly_smiling_face:  

Given that this doesn't match how typing works in real life, where you *have* to use the backspace button to fix mistakes, I'm not so sure if it would be worth the added maintenance burden. There doesn't seem to be a lot of demand for it regardless. Feel free to correct me if you think I'm wrong, though.
