### ISSUE TITLE
[Language Request]: Korean

### ISSUE THREAD

**Issue by RuboGubo** [bragefuglseth/keypunch#78]
### English Name

Korean

### Native Name

한국어

### Orthography
Korean is pronounced using a unique writing system called Hangul. It is composed of combinations of 17 consonants and 11 vowels.

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

It does not use the Latin alphabet

**Comment by RuboGubo** [comment]
FYI: Words per min does not work in Korean, a better measure would be characters per min

**Comment by bragefuglseth** [comment]
Hi, thanks for the report! Korean is already supported by Keypunch (#8), so you should be able to choose it from the language dialog.

I’ve thought of the WPM calculation issues for CJK characters, and that deserves its own issue tbh. I’m planning to do some changed to how the statistics machinery works in general, though, which would be good to do before looking into special casing of CJK characters.
