### ISSUE TITLE
[Language Request]: Add kabyle language

### ISSUE THREAD

**Issue by BoFFire** [bragefuglseth/keypunch#82]
### English Name

Kabyle

### Native Name

Taqbaylit

### Orthography

Kabyle or Taqbaylit, is a Berber language spoken mainly in northern Algeria and among diaspora communities. Written primarily in the Latin alphabet, Kabyle includes letters such as `a, b, c, č, d, ḍ, e, f, g, ǧ, ɣ, h, ḥ, i, j, k, l, m, n, q, r, ṛ, s, ṣ, t, ṭ, u, w, x, y, z, ẓ and ɛ`. Common punctuation includes the comma (,), period (.), question mark (?), exclamation mark (!), and dash (-).

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

I can assist with testing and providing some text resources. Example : https://www.amyag.com/f/NTU5Mw/%C9%A3e%E1%BA%93%E1%BA%93

**Comment by BoFFire** [comment]
Started the app translation here : https://github.com/bragefuglseth/keypunch/pull/83

**Comment by bragefuglseth** [comment]
Hi, and thanks for the request! I've added an initial implementation of the Kabyle text generation. You can test it by building the app from source (by following the instructions in CONTRIBUTING.md) and selecting Taqbaylit in the language selection dialog. Let me know if everything looks ok.

**Comment by BoFFire** [comment]
Hi @bragefuglseth A new Kabyle list is now submitted here : https://github.com/bragefuglseth/keypunch/pull/88
