### ISSUE TITLE
[Language Request]: Vietnamese

### ISSUE THREAD

**Issue by thieuson1984** [bragefuglseth/keypunch#86]
### English Name

Vietnamese

### Native Name

Tiếng Việt

### Orthography

The Vietnamese alphabet contains 29, including seven letters using four: ⟨ă⟩, ⟨â⟩, ⟨ê⟩, ⟨ô⟩, ⟨ơ⟩, ⟨ư⟩, and ⟨đ⟩. There are an additional five diacritics used to designate (as in ⟨à⟩, ⟨á⟩, ⟨ả⟩, ⟨ã⟩, and ⟨ạ⟩). The complex vowel system and the large number of letters with diacritics, which can stack twice on the same letter (e.g. nhất meaning 'first'), makes it easy to distinguish the Vietnamese orthography from other writing systems that use the Latin script.

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

**Comment by bragefuglseth** [comment]
Hi, thanks for the language request! I've attempted to spin up an initial text generation implementation for Vietnamese. To test it, you can build a development version of the app using the instructions in CONTRIBUTING.md and select Vietnamese in the text language dialog.

Let me know if it looks good to you or if you encounter any issues!

**Comment by bragefuglseth** [comment]
Let's ship this for 4.0 and hope it's good enough.

**Comment by thieuson1984** [comment]
> Let's ship this in 5.0 and hope it's good enough.

I've tested and it's very good. Thank you
