### ISSUE TITLE
[Language Request]: Finnish

### ISSUE THREAD

**Issue by oimu4** [bragefuglseth/keypunch#90]
### English Name

Finnish

### Native Name

Suomi

### Orthography

Finnish is very similar to English alphabet but we have Ä, Ö and Å. We use nordic qwerty layout. It's pretty much the same but we just have those 3 extra letters

### Implementation Assistance

- [X] I am proficient enough in this language to spot mistakes and unnatural words
- [X] I can assist with testing and reviewing the language implementation

### Additional Information

We don't have "the" or "a" in Finnish.

**Comment by bragefuglseth** [comment]
Hi, thanks for the language request! I've added an initial implementation of Finnish text generation; now all that's left is to test it. You can do so by building a development version of the app (pretty straightforward process with GNOME Builder, see the instructions in CONTRIBUTING.md). Let me know if everything looks good, and I might even be able to get it out in a new release tomorrow!

**Comment by oimu4** [comment]
Everything seems good and thanks for making this
